apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cjob
spec:
  schedule: '*/1 * * * *'
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 30
      template:
        spec:
          containers:
          - image: busybox
            name: cjob
            args:
            - /bin/sh
            - -c
            - date; echo Hell world
          restartPolicy: Never
